name: Missing Spec Rejecter

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Check for Spec changes
      uses: the-nusbaum/missing_spec_rejector@main
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
        TARGET: ${{ github.event.pull_request.base.ref }}
